### ISSUE TITLE
question and request

### ISSUE THREAD

**Issue by duyduc27** [detroitbecometext/detroitbecometext.github.io#3]
Thank you for your great work. I really appreciate all the work you have done, it helped me so much. I would like to ask a question and put some requests.

- Have you guys finished the project yet? Since I saw some chapters were still in progress status (26, 28, 31.2, ...) 
- I would like to read magazines content in the game also. So please add them on an extra chapter.
- Chloe's dialogues (in main screen) are interesting as well! Therefore maybe we should add them on the extra chapter above too.

Thank you and have a nice day.

**Comment by detroitbecometext** [comment]
Hi,

Thank you for your appreciation of the project!

No, this is still a work in progress. There are some main dialogues missing, and probably a lot of the side dialogues as well, but those are harder to find.  

Adding Chloe's lines is a good idea, I'll try to do it for the next update.  
As for the magazines, they are already available on the [detroit wiki](https://detroit-become-human.fandom.com/wiki/Magazine), so I'll probably just add a link to it.

Have a great day!

**Comment by CyberLifeBots** [comment]
Hey, great project! We will share your website with our facebook group : https://www.facebook.com/groups/DetroitBecomeHumanGame

You should join us, it currently has over 16k members. The work you guys have done on this project is amazing! Keep up the hard work! Also, if you can please add a related websites or media section so groups like us can associate with you guys! Thank you again!

**Comment by detroitbecometext** [comment]
Hi, 

Thank you! I don't really use facebook, but I see you also have a discord server, so I'll probably join you there instead !
Having a "related links" section is a good idea, I added it to the todo list for the next update.

Thank you again for supporting the project!

**Comment by CyberLifeBots** [comment]
Awesome, let me know your username once you're in!

**Comment by detroitbecometext** [comment]
> Awesome, let me know your username once you're in!

Hey, just letting you know that I joined the server a few days ago! My username starts with "P", you should find it easily if you look in the channel for new users.

**Comment by CyberLifeBots** [comment]
There are 2, Pithaya and pixalatedsquid, my guess is Pithaya?

**Comment by detroitbecometext** [comment]
> There are 2, Pithaya and pixalatedsquid, my guess is Pithaya?

Yes, Pithaya is the right one !
